name: Publish gem

on:
  push:
    branches:
      - main
      - add-gem-release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/local/rubies
        key: ruby-2.6.5
    - uses: ruby/setup-ruby@v1.62.0
      id: ruby
      with:
        ruby-version: 2.6.5
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    # https://intuit.github.io/auto/docs/configuration/non-npm
    - name: Install auto
      run: curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.28.0/auto-linux.gz | gunzip > ~/auto && chmod a+x ~/auto
    - name: Log
      run: ls -a
    - name: Release gem
      run: ~/auto shipit
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
